// This file is auto-generated by the Supabase CLI.
// Run: npx supabase gen types typescript --project-id <project-id> > src/lib/supabase/types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      ingredient_icons: {
        Row: {
          id: string;
          name: string;
          name_normalized: string;
          icon_url: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          name_normalized: string;
          icon_url: string;
          created_at?: string;
        };
        Update: {
          name?: string;
          name_normalized?: string;
          icon_url?: string;
        };
        Relationships: [];
      };
      recipe_covers: {
        Row: {
          id: string;
          title: string;
          title_normalized: string;
          cover_url: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          title_normalized: string;
          cover_url: string;
          created_at?: string;
        };
        Update: {
          title?: string;
          title_normalized?: string;
          cover_url?: string;
        };
        Relationships: [];
      };
      ingredients: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          category: string;
          quantity: number | null;
          unit: string | null;
          expiry_date: string | null;
          notes: string | null;
          icon_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          category: string;
          quantity?: number | null;
          unit?: string | null;
          expiry_date?: string | null;
          notes?: string | null;
          icon_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          category?: string;
          quantity?: number | null;
          unit?: string | null;
          expiry_date?: string | null;
          notes?: string | null;
          icon_url?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      recipes: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          cuisine: string | null;
          servings: number | null;
          prep_time_minutes: number | null;
          cook_time_minutes: number | null;
          difficulty: string | null;
          ingredients: Json;
          steps: Json;
          nutrition_estimate: Json | null;
          tags: string[] | null;
          generated_by: string | null;
          created_by: string | null;
          cover_image_url: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string | null;
          cuisine?: string | null;
          servings?: number | null;
          prep_time_minutes?: number | null;
          cook_time_minutes?: number | null;
          difficulty?: string | null;
          ingredients: Json;
          steps: Json;
          nutrition_estimate?: Json | null;
          tags?: string[] | null;
          generated_by?: string | null;
          created_by?: string | null;
          cover_image_url?: string | null;
          created_at?: string;
        };
        Update: {
          title?: string;
          description?: string | null;
          cuisine?: string | null;
          servings?: number | null;
          prep_time_minutes?: number | null;
          cook_time_minutes?: number | null;
          difficulty?: string | null;
          ingredients?: Json;
          steps?: Json;
          nutrition_estimate?: Json | null;
          tags?: string[] | null;
          cover_image_url?: string | null;
        };
        Relationships: [];
      };
      saved_recipes: {
        Row: {
          id: string;
          user_id: string;
          recipe_id: string;
          saved_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          recipe_id: string;
          saved_at?: string;
        };
        Update: {
          saved_at?: string;
        };
        Relationships: [];
      };
      taste_signals: {
        Row: {
          id: string;
          user_id: string;
          signal_type: string;
          signal_value: string;
          confidence: number;
          source: string;
          context: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          signal_type: string;
          signal_value: string;
          confidence?: number;
          source?: string;
          context?: string | null;
          created_at?: string;
        };
        Update: {
          signal_type?: string;
          signal_value?: string;
          confidence?: number;
          source?: string;
          context?: string | null;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          display_name: string | null;
          avatar_url: string | null;
          dietary_restrictions: string[] | null;
          preferred_cuisine: string[] | null;
          nickname: string | null;
          dietary_preferences: Json | null;
          allergies: string[] | null;
          cooking_level: string | null;
          kitchen_equipment: string[] | null;
          default_servings: string | null;
          taste_profile: Json | null;
          fat_loss_mode: boolean | null;
          daily_calorie_target: number | null;
          daily_protein_target_g: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          display_name?: string | null;
          avatar_url?: string | null;
          dietary_restrictions?: string[] | null;
          preferred_cuisine?: string[] | null;
          nickname?: string | null;
          dietary_preferences?: Json | null;
          allergies?: string[] | null;
          cooking_level?: string | null;
          kitchen_equipment?: string[] | null;
          default_servings?: string | null;
          taste_profile?: Json | null;
          fat_loss_mode?: boolean | null;
          daily_calorie_target?: number | null;
          daily_protein_target_g?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          display_name?: string | null;
          avatar_url?: string | null;
          dietary_restrictions?: string[] | null;
          preferred_cuisine?: string[] | null;
          nickname?: string | null;
          dietary_preferences?: Json | null;
          allergies?: string[] | null;
          cooking_level?: string | null;
          kitchen_equipment?: string[] | null;
          default_servings?: string | null;
          taste_profile?: Json | null;
          fat_loss_mode?: boolean | null;
          daily_calorie_target?: number | null;
          daily_protein_target_g?: number | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      cook_log: {
        Row: {
          id: string;
          user_id: string;
          recipe_title: string;
          nutrition: Json | null;
          cooked_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          recipe_title: string;
          nutrition?: Json | null;
          cooked_at?: string;
        };
        Update: {
          recipe_title?: string;
          nutrition?: Json | null;
          cooked_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
